apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:latest
        ports:
        - containerPort: 8123
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            memory: 1Gi
            cpu: 500m
        volumeMounts:
        - name: homeassistant
          mountPath: /config
      volumes:
      - name: homeassistant
        persistentVolumeClaim:
          claimName: homeassistant-pvc