# Home Assistant Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd # <--- CORRETTO: ArgoCD gestisce le App solo nel suo namespace
spec:
  project: homeassistant-project
  source:
    repoURL: https://github.com/AndyCpX/automata
    path: manifests
    targetRevision: ha
  destination:
    server: https://kubernetes.default.svc # <--- CORRETTO: URL del cluster interno
    namespace: default # <--- Il namespace dove verrà installato Home Assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5m
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground